import Anthropic from '@anthropic-ai/sdk';
import fs from 'fs';
import path from 'path';

interface TestResult {
  title: string[];
  status: 'passed' | 'failed' | 'skipped' | 'timedOut' | 'interrupted';
  duration: number;
  errors?: Array<{ message: string; stack?: string }>;
  tags?: string[];
}

interface TestSuite {
  title: string;
  tests?: TestResult[];
  suites?: TestSuite[];
}

interface PlaywrightReport {
  stats: {
    total: number;
    passed: number;
    failed: number;
    skipped: number;
    duration: number;
  };
  suites?: TestSuite[];
}

function extractTests(suite: TestSuite, parentTitle = ''): TestResult[] {
  const prefix = parentTitle ? `${parentTitle} > ` : '';
  const tests: TestResult[] = [];

  if (suite.tests) {
    for (const t of suite.tests) {
      tests.push({ ...t, title: [`${prefix}${suite.title}`, ...t.title] });
    }
  }
  if (suite.suites) {
    for (const s of suite.suites) {
      tests.push(...extractTests(s, `${prefix}${suite.title}`));
    }
  }
  return tests;
}

function buildReportSummary(report: PlaywrightReport): string {
  const { stats } = report;
  const allTests: TestResult[] = [];
  for (const suite of report.suites ?? []) {
    allTests.push(...extractTests(suite));
  }

  const failures = allTests.filter((t) => t.status === 'failed' || t.status === 'timedOut');
  const passed   = allTests.filter((t) => t.status === 'passed');
  const skipped  = allTests.filter((t) => t.status === 'skipped');

  const lines: string[] = [
    `=== PLAYWRIGHT TEST REPORT ===`,
    `Total: ${stats.total} | Passed: ${stats.passed} | Failed: ${stats.failed} | Skipped: ${stats.skipped}`,
    `Duration: ${(stats.duration / 1000).toFixed(1)}s`,
    '',
  ];

  if (failures.length > 0) {
    lines.push('--- FAILURES ---');
    for (const t of failures) {
      lines.push(`[${t.status.toUpperCase()}] ${t.title.join(' > ')}`);
      for (const err of t.errors ?? []) {
        lines.push(`  Error: ${err.message?.split('\n')[0] ?? '(no message)'}`);
      }
    }
    lines.push('');
  }

  lines.push('--- PASSED ---');
  for (const t of passed) lines.push(`[PASS] ${t.title.join(' > ')}`);

  return lines.join('\n');
}

export async function analyzeTestReport(
  reportPath: string,
  outputPath: string,
): Promise<string> {
  if (!fs.existsSync(reportPath)) {
    throw new Error(`Report not found: ${reportPath}`);
  }

  const report: PlaywrightReport = JSON.parse(fs.readFileSync(reportPath, 'utf-8'));
  const summary = buildReportSummary(report);
  const hasFail = (report.stats.failed ?? 0) > 0;

  console.log('\n[AI Report Analyzer] Sending test results to Claude...\n');

  const client = new Anthropic();

  const stream = client.messages.stream({
    model: 'claude-opus-4-7',
    max_tokens: 2048,
    thinking: { type: 'adaptive' },
    system: [
      {
        type: 'text',
        text: `You are a senior SDET reviewing a Playwright test report. Your job is to produce a concise, actionable Markdown report with:
1. **Executive Summary** — 2–3 sentences on overall health
2. **Failure Analysis** (if any) — root cause hypothesis and recommended fix for each failed test
3. **Anti-Bot / Network Notes** — flag any graceful-fallback patterns (blockedByAntiBot) and explain what they mean
4. **Next Actions** — prioritized list of things to investigate or fix
5. **Pass Rate Badge** — e.g. ✅ 100% | ⚠️ 80% | ❌ 60%

Keep it under 600 words. Be precise — mention test names, error messages, and concrete fixes.`,
        cache_control: { type: 'ephemeral' },
      },
    ],
    messages: [
      {
        role: 'user',
        content: `Here is the Playwright test report summary:\n\n\`\`\`\n${summary}\n\`\`\`\n\nGenerate the Markdown report.`,
      },
    ],
  });

  let aiContent = '';
  process.stdout.write('[Claude] ');
  for await (const event of stream) {
    if (
      event.type === 'content_block_delta' &&
      event.delta.type === 'text_delta'
    ) {
      process.stdout.write(event.delta.text);
      aiContent += event.delta.text;
    }
  }
  process.stdout.write('\n');

  const finalMsg = await stream.finalMessage();
  const inputTokens  = finalMsg.usage.input_tokens;
  const outputTokens = finalMsg.usage.output_tokens;

  const header = [
    `# AI Test Report — ${new Date().toISOString().slice(0, 10)}`,
    '',
    `> Generated by Claude Opus 4.7 | Input: ${inputTokens} tok | Output: ${outputTokens} tok`,
    '',
  ].join('\n');

  const full = header + aiContent;
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, full, 'utf-8');

  console.log(`\n\n[AI Report Analyzer] Written to ${outputPath}`);
  return full;
}
