import Anthropic from '@anthropic-ai/sdk';
import fs from 'fs';
import path from 'path';

export interface ScenarioGeneratorOptions {
  userStory: string;
  outputPath: string;
  workflowType?: string;
  testRailPrefix?: string;
}

const SYSTEM_PROMPT = `You are a senior SDET specializing in Playwright TypeScript test automation.
Your job is to generate typed test scenario files following this exact framework architecture.

The project uses a BaseTestScenario<TWorkflow, TExpectedResults, TActionsData> generic pattern:
- TWorkflow: union string type for workflow names (e.g. 'search-and-validate' | 'empty-search-validation')
- TExpectedResults: interface describing what to assert
- TActionsData: interface describing test input data

Output rules:
1. Emit ONLY valid TypeScript — no prose before or after
2. Use the exact import paths shown in examples
3. Use \`as const\` on data objects for type narrowing
4. Include TestRail IDs (SRCH-TC-XXX format), tags (@search, @regression, etc.)
5. Add \`skip: true\` for scenarios that can't yet be automated with a TODO comment
6. Write 4-8 scenarios: happy paths, edge cases, negative tests
7. Every scenario MUST have a unique testRailId
8. Export the array as \`const scenarios: SomeScenario[]\`

Example output structure (follow this pattern exactly):
\`\`\`typescript
import type { BaseTestScenario } from '@interface/interface.index';

type MyWorkflow = 'workflow-a' | 'workflow-b';
interface MyExpected { containsText?: string; }
interface MyActions { query?: string; }
export type MyScenario = BaseTestScenario<MyWorkflow, MyExpected, MyActions>;

export const scenarios: MyScenario[] = [
  {
    testName: '...',
    tags: ['@tag'],
    testRailId: 'SRCH-TC-001',
    workflow: 'workflow-a',
    actionsData: { query: 'example' },
    expectedResults: { containsText: 'example' },
  },
];
\`\`\``;

export async function generateScenarios(opts: ScenarioGeneratorOptions): Promise<string> {
  const { userStory, outputPath, workflowType = 'search', testRailPrefix = 'SRCH' } = opts;

  console.log('\n[AI Scenario Generator] Sending user story to Claude...\n');
  console.log(`User Story:\n  "${userStory}"\n`);

  const client = new Anthropic();

  const stream = client.messages.stream({
    model: 'claude-opus-4-7',
    max_tokens: 3000,
    thinking: { type: 'adaptive' },
    system: [
      {
        type: 'text',
        text: SYSTEM_PROMPT,
        cache_control: { type: 'ephemeral' },
      },
    ],
    messages: [
      {
        role: 'user',
        content: [
          {
            type: 'text',
            text: `Generate a Playwright test scenario file in TypeScript for this user story:

"${userStory}"

Constraints:
- Workflow category: ${workflowType}
- TestRail prefix: ${testRailPrefix}
- Framework: our Redfin search automation layered architecture
- Emit ONLY the TypeScript file content — no markdown fences, no explanation`,
          },
        ],
      },
    ],
  });

  let tsContent = '';
  process.stdout.write('[Claude] ');
  for await (const event of stream) {
    if (
      event.type === 'content_block_delta' &&
      event.delta.type === 'text_delta'
    ) {
      process.stdout.write(event.delta.text);
      tsContent += event.delta.text;
    }
  }
  process.stdout.write('\n');

  // Strip markdown fences if Claude included them despite instructions
  const clean = tsContent
    .replace(/^```(?:typescript|ts)?\n?/m, '')
    .replace(/\n?```$/m, '')
    .trim();

  const header = [
    `// ─────────────────────────────────────────────────────────────────────────`,
    `// AI-GENERATED by Claude Opus 4.7 — ${new Date().toISOString().slice(0, 10)}`,
    `// User story: "${userStory}"`,
    `// Review and adjust before committing to production.`,
    `// ─────────────────────────────────────────────────────────────────────────`,
    '',
  ].join('\n');

  const finalTs = header + clean + '\n';
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, finalTs, 'utf-8');

  const finalMsg = await stream.finalMessage();
  console.log(
    `\n\n[AI Scenario Generator] Written to ${outputPath}`,
    `(${finalMsg.usage.input_tokens} in / ${finalMsg.usage.output_tokens} out tokens)`,
  );

  return finalTs;
}
